version: "3.3"

services:
  bot:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    volumes:
      - ./volumes:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
