name: Test and Deploy in server

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      VPN_URL_API: ${{ secrets.VPN_URL_API }}
    steps:
      - uses: actions/checkout@v3

      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5

      - name: run tests
        run: |
          cd ./src
          go test ./tests/...

  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3

      - name: generate envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

          envkey_VPN_URL_API: ${{ secrets.VPN_URL_API }}
          envkey_TOTAL_VPN_PRICE: ${{ secrets.TOTAL_VPN_PRICE }}
          envkey_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          envkey_ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
          envkey_PROVIDER_TOKEN: ${{ secrets.PROVIDER_TOKEN }}

          some_other_variable: foobar
          directory: ./
          file_name: .env
          fail_on_empty: true

      - name: get last updates
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./"
          target: "~/my-vpn-shop"

      - name: build and start project
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd my-vpn-shop
            make up
