name: Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      VPN_URL_API: ${{ secrets.VPN_URL_API }}
    steps:
      - uses: actions/checkout@v3

      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5

      - name: run tests
        run: |
          cd ./src
          go test ./tests/...
